### ISSUE TITLE
Is rust-embedded a part of the Increasing Rust's Reach project?

### ISSUE THREAD

**Issue by samdolt** [rust-lang-nursery/embedded-wg#32]
The Increasing  [ Rust's Reach project](https://blog.rust-lang.org/2017/06/27/Increasing-Rusts-Reach.html)  was announced yesterday.

For some time now, I want to help on the embedded side of Rust, but it's not easy to know where to focus, what is needed first.  

So what do you think about participating in the Rust's Reach Project? Are there mentors available?

**Comment by japaric** [comment]
Last year Increasing Rust's Reach projects were limited to those announced in the blog post. This year the plan is to have some of / all the four domain WG participate in the program. I can't say more than that I think (I probably already said more than I should have, actually :sweat_smile:). Subscribe to the blog and wait for the official announcement of this year edition.

> For some time now, I want to help on the embedded side of Rust, but it's not easy to know where to focus, what is needed first.

The README now lists on going community efforts; check it out! There's also a `call-for-action` label that we are using in the issue tracker to tag issues where we need the community's help. There may not be many tasks listed right now but we'll put out more work items as we go along. The embedded WG is just getting started :tada:
